#!/bin/bash
# This script loads the mugqic stack in on the host 
# It also loads the lmod software 


export MUGQIC_INSTALL_HOME=/cvmfs/soft.mugqic/CentOS6


usage (){
  echo -e "\nUsage: $0 [ [ -V <X.X.X> ] [ <cmd> ]" 1>&2;
  echo -e "\nOPTION"
  echo -e "\t-V  GenPipes version (will default to latest release)"
  echo -e "\t-v  Vebose mode, makes the parrot talk"
  echo
}

export QUIET="-d clear"

while getopts ":vV:h" opt; do
  case $opt in
    v)
      unset QUIET
      ;;
    V)
      export PIPELINE_VERSION=/${OPTARG}
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))
# move the exec line to a script
if [ $# -gt 0 ] ; then
  function finish {
    rm "${genpipes_script}"
  }
  genpipes_script=$(mktemp /tmp/genpipes_script.XXXXXX)
  trap finish EXIT
  chmod 755 "${genpipes_script}"
  echo '#!/bin/bash' >> "${genpipes_script}"
  echo "$@" >> "${genpipes_script}"
fi

# load cvmfs
if [ "${genpipes_script}" ]; then
  bash -ilc "${genpipes_script}"
else
  bash -il
fi
